config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }, path_names: {sign_in: 'login', sign_out: 'logout'}

  root to: "index#show", page_alias: 'home', as: 'home'

  namespace :admin do
    get '', to: "index#index", as: 'home_admin'
    resources :categories, :posts, :pages, :users, :widgets, :widget_positions, :roles, :tags
    resources :comments, except: [:create]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
    end
  end

  resources :comments, only: [:destroy]

  resources :profiles, only: [:show, :update]

  post 'comments/add', to: 'comments#add'
  post 'blog/add_post', to: 'posts#add_post', as: 'add_post'

  get 'blog/:category_alias', to: 'categories#show', as: 'category'
  get 'blog/:category_alias/:post_alias', to: 'posts#show', as: 'post'
  get 'search', to: 'search#show', as: 'search'
  get 'tags/:tag', to: 'tags#show', as: 'tags'
  get 'get-pagination', to: 'application#get_pagination', as: 'pagination'
  get ':page_alias', to: 'pages#show', as: 'page'
end

app/views/admin/pages/_form.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header d-flex p-0">
        <ul class="nav nav-pills mr-auto p-2">
          <li class="nav-item"><a class="nav-link active" href="#tab_1" data-toggle="tab">General</a></li>
          <li class="nav-item"><a class="nav-link" href="#tab_2" data-toggle="tab">Seo</a></li>
          <li class="nav-item"><a class="nav-link" href="#tab_3" data-toggle="tab">Widgets</a></li>
        </ul>
      </div>
      <%= nested_form_for [:admin, @model], html: {multipart: true} do |f| %>
        <div class="card-body">
          <div class="tab-content">
            <div class="tab-pane active" id="tab_1">
              <div class="row">
                <div class="col-md-8">
                  <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                  </div>
                  <div class="form-group">
                    <%= f.label :alias %>
                    <%= f.text_field :alias, class: 'form-control' %>
                  </div>

                  <div class="form-group">
                    <%= f.label :intro_text %>
                    <%= f.text_area :intro_text, class: 'form-control' %>
                  </div>

                  <div class="form-group">
                    <%= f.label :text %>
                    <%= f.cktext_area :text, class: 'form-control editor' %>
                  </div>

                  <div class="form-group">
                    <%= image_tag(@model.image.name, width: 300) if @model.image.present? %>
                  </div>

                  <%= f.fields_for :image do |image_form| %>
                    <% if @model.image.present? && !@model.image.name.blank? %>
                      <p>
                        <label>
                          <%= image_form.check_box :remove_name %>
                          Remove image
                        </label>
                      </p>
                    <% end %>
                    <div class="form-group">
                      <div class="custom-file">
                        <%= image_form.label :image, value: 'Choose file', class: 'custom-file-label' %>
                        <%= image_form.file_field :name, class: 'custom-file-input', id: 'customFile' %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="tab-pane" id="tab_2">
              <div class="row">
                <div class="col-md-8">
                  <div class="form-group">
                    <%= f.label :h1 %>
                    <%= f.text_field :h1, class: 'form-control' %>
                  </div>
                  <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class: 'form-control' %>
                  </div>
                  <div class="form-group">
                    <%= f.label :description %>
                    <%= f.text_field :description, class: 'form-control' %>
                  </div>
                  <div class="form-group">
                    <%= f.label :breadcrumb %>
                    <%= f.text_field :breadcrumb, class: 'form-control' %>
                  </div>
                </div>
              </div>
            </div>
            <div class="tab-pane" id="tab_3">
              <div class="row">
                <div class="col-md-8">
                  <% Widget.find_each do |widget| %>
                    <div class="row mb-2">
                      <div class="col-sm-6">
                        <div class="icheck-primary">
                          <%= check_box('widget_pages', 'widget_ids', {multiple: true, checked: checked?(@widget_ids, widget.id), id: "checkboxPrimary#{widget.id}"}, widget.id, nil) %>
                          <label for="<%= "checkboxPrimary#{widget.id}" %>"><%= widget.wname %></label>
                        </div>
                      </div>
                      <div class="col-sm-2">
                        <% sort = @model.widget_pages.for(widget).sort %>
                        <%= text_field_tag "widget_positions[#{widget.id}]", sort.is_a?(Numeric) ? sort : 500, class: 'form-control' %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <br>
          <%= submit_tag 'Save', class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/pages/_page_item_list.html.erb
<tr class="jsgrid-row">
  <td class="jsgrid-cell"><%= page.id %></td>
  <td class="jsgrid-cell"><%= image_tag(page.image.name.url(:small_thumb), width: 100) if page.image.present? %></td>
  <td class="jsgrid-cell"><%= page.name %></td>
  <td class="jsgrid-cell"><%= page.alias %></td>
  <td class="jsgrid-cell">
    <%= link_to page_path(page.alias), target: "_blank" do %>
      <i class="fa fa-eye"></i>
    <% end %>
    &nbsp;
    <%= link_to edit_admin_page_path(page) do %>
      <i class="fa fa-edit"></i>
    <% end %>
    &nbsp;
    <%= link_to admin_page_path(page), method: :delete, data: {:confirm => 'Are you sure?'} do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/admin/pages/edit.html.erb
<%= render 'form' %>

app/views/admin/pages/index.html.erb
<div class="row">
  <div class="col-12">
    <%= link_to 'Create page', new_admin_page_path, role: 'button', class: 'mb-4 btn btn-primary' %>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <div id="jsGrid1" class="jsgrid">
      <table class="jsgrid-table">
        <tr class="jsgrid-header-row">
          <th style="width:50px;" class="jsgrid-header-cell">id</th>
          <th style="width:130px;" class="jsgrid-header-cell">photo</th>
          <th class="jsgrid-header-cell">name</th>
          <th class="jsgrid-header-cell">alias</th>
          <th style="width:80px;" class="jsgrid-header-cell"></th>
        </tr>
        <%= render partial: 'admin/pages/page_item_list', collection: @model, as: 'page' %>
      </table>
      <%= will_paginate @model, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/admin/pages/new.html.erb
<%= render 'form' %>