config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }, path_names: {sign_in: 'login', sign_out: 'logout'}

  root to: "index#show", page_alias: 'home', as: 'home'

  namespace :admin do
    get '', to: "index#index", as: 'home_admin'
    resources :categories, :posts, :pages, :users, :widgets, :widget_positions, :roles, :tags
    resources :comments, except: [:create]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
    end
  end

  resources :comments, only: [:destroy]

  resources :profiles, only: [:show, :update]

  post 'comments/add', to: 'comments#add'
  post 'blog/add_post', to: 'posts#add_post', as: 'add_post'

  get 'blog/:category_alias', to: 'categories#show', as: 'category'
  get 'blog/:category_alias/:post_alias', to: 'posts#show', as: 'post'
  get 'search', to: 'search#show', as: 'search'
  get 'tags/:tag', to: 'tags#show', as: 'tags'
  get 'get-pagination', to: 'application#get_pagination', as: 'pagination'
  get ':page_alias', to: 'pages#show', as: 'page'
end

app/views/shared/_comment.html.erb
<% collection.hash_tree.each do |comment, sub_item| %>
  <div class="media">
    <div class="media-left">
      <%= image_tag comment.user.profile.image.name, class: 'media-object' if comment.user.present? && comment.user.profile.image.present? %>
    </div>
    <div class="media-body">
      <div class="media-heading">
        <h4><%= comment.user.try(:profile).present? ? comment.user.profile.name : comment.name %></h4>
        <span class="time"><%= comment.created_at.ago_in_words %></span>
        <% if current_user.try(:is_cms_user?) %>
          <%= link_to comment_path(comment), remote: true, method: :delete, class: 'comment_destroy' do %>
            <i class="fa fa-trash"></i>
          <% end %>
        <% end %>
      </div>
      <p><%= comment.body %></p>
      <a href="#" data-id="<%= comment.id %>" class="reply">Reply</a>
      <%= render partial: 'shared/comment', locals: {collection: comment.children} if comment.children.present? %>
    </div>
  </div>
<% end %>

app/views/shared/_comments.html.erb
<% if @model.comments.present? %>
  <div class="section-row">
    <div class="section-title">
      <h3 class="title"><%= @model.comments.count %> Comments</h3>
    </div>
    <div class="post-comments">
      <%= render partial: 'shared/comment', locals: {collection: @model.comments} %>
    </div>
  </div>
<% else %>
  <div class="section-row">
    <div class="post-comments">
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%= bottom2_position %>

<footer id="footer">

  <div class="container">

    <div class="row">
      <div class="col-md-4">
        <div class="footer-widget">
          <div class="footer-logo">
            <a href="index.html" class="logo"><%= image_tag "logo-alt.png" %></a>
          </div>
          <p>Nec feugiat nisl pretium fusce id velit ut tortor pretium. Nisl purus in mollis nunc sed. Nunc non blandit
            massa enim nec.</p>
          <ul class="contact-social">
            <li><a href="#" class="social-facebook"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#" class="social-twitter"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#" class="social-google-plus"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#" class="social-instagram"><i class="fa fa-instagram"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="footer-widget">
          <h3 class="footer-title">Categories</h3>
          <div class="category-widget">
            <ul>
              <%= render partial: 'shared/blocks/category_item_list', collection: @categories, as: :category %>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <%= render 'widgets/tags_widget' %>
      </div>
    </div>


    <div class="footer-bottom row">
      <div class="col-md-6 col-md-push-6">
        <%= build_mmmenu(@bottom_menu, templates_path: 'mmmenu/bottom_menu') %>
      </div>
      <div class="col-md-6 col-md-pull-6">
        <div class="footer-copyright">

          Copyright &copy;<script>document.write(new Date().getFullYear());</script>
          All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by
          <a href="https://colorlib.com" target="_blank">Colorlib</a>

        </div>
      </div>
    </div>

  </div>

</footer>


<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/shared/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= "
  <div class='alert-success p-2 mb-2 message-item'>
  <div class=\"container\">
    <div class=\"row\">
      <div class=\"col-xs-11\">#{notice}</div>
      <div class=\"col-xs-1 text-right\"><i class=\"fa fa-close\"></i></div>
    </div>
  </div>
</div>
".html_safe if notice.present? %>
<%= "<div class='alert-success p-2 mb-2 message-item'>
  <div class=\"container\">
    <div class=\"row\">
      <div class=\"col-xs-11\">#{alert}</div>
      <div class=\"col-xs-1 text-right\"><i class=\"fa fa-close\"></i></div>
    </div>
  </div>
</div>
".html_safe if alert.present? %>
<div class="top_menu">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <% if user_signed_in? %>
          <span>Здравствуйте, <%= link_to current_user.email, profile_path(current_user.profile) if current_user.try(:profile).present? %></span>
          <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to 'Войти', new_user_session_path %>
          или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<header id="header">

  <div id="nav">

    <div id="nav-top">
      <div class="container">

        <ul class="nav-social">
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
          <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        </ul>


        <div class="nav-logo">
          <%= link_to home_path, class: 'logo' do %>
            <%= image_tag "logo.png" %>
          <% end %>
        </div>


        <div class="nav-btns">
          <button class="aside-btn"><i class="fa fa-bars"></i></button>
          <button class="search-btn"><i class="fa fa-search"></i></button>
          <div id="nav-search">
            <%= form_tag(search_path, method: "get", enforce_utf8: false) do %>
              <%= text_field_tag :q, nil, {class: 'input', placeholder: 'Enter your search...'} %>
            <% end %>
            <button class="nav-close search-close">
              <span></span>
            </button>
          </div>
        </div>

      </div>
    </div>


    <div id="nav-bottom">
      <div class="container">
        <%= build_mmmenu(@main_menu, templates_path: 'mmmenu/main_menu') %>
      </div>
    </div>
    <div id="nav-aside">
      <%= build_mmmenu(@aside_menu, templates_path: 'mmmenu/aside_menu') %>
      <button class="nav-close nav-aside-close"><span></span></button>
    </div>
  </div>

  <%= yield :page_header %>

</header>

app/views/shared/_post_list.html.erb
<% if posts.present? %>
  <%= render "posts/post_v1", post: posts[:first] if posts[:first].present? %>

  <% if posts[:group1].present? %>
    <div class="row">
      <%= render partial: 'posts/post_v2', collection: posts[:group1], as: :post %>
    </div>
  <% end %>

  <%= render partial: 'posts/post_v3', collection: posts[:group2], as: :post if posts[:group2].present? %>
<% end %>

app/views/shared/_sidebar.html.erb
<%= render "widgets/social_widget" rescue nil %>
<%= render "widgets/category_widget" rescue nil %>
<%= render "widgets/post_widget" rescue nil %>