config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }, path_names: {sign_in: 'login', sign_out: 'logout'}

  root to: "index#show", page_alias: 'home', as: 'home'

  namespace :admin do
    get '', to: "index#index", as: 'home_admin'
    resources :categories, :posts, :pages, :users, :widgets, :widget_positions, :roles, :tags
    resources :comments, except: [:create]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
    end
  end

  resources :comments, only: [:destroy]

  resources :profiles, only: [:show, :update]

  post 'comments/add', to: 'comments#add'
  post 'blog/add_post', to: 'posts#add_post', as: 'add_post'

  get 'blog/:category_alias', to: 'categories#show', as: 'category'
  get 'blog/:category_alias/:post_alias', to: 'posts#show', as: 'post'
  get 'search', to: 'search#show', as: 'search'
  get 'tags/:tag', to: 'tags#show', as: 'tags'
  get 'get-pagination', to: 'application#get_pagination', as: 'pagination'
  get ':page_alias', to: 'pages#show', as: 'page'
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  validates :name, :wname, presence: true
  belongs_to :position, class_name: 'WidgetsPosition'
  has_many :widget_pages, dependent: :destroy
end

app/controllers/admin/widgets_controller.rb
class Admin::WidgetsController < Admin::AdminController
  before_action :get_model, only: [:edit, :update, :show]

  def index
    @h1 = 'Widgets'
    @model = Widget.all.paginate(:page => params[:page])
  end

  def new
    @h1 = 'Create widget'
    @model = Widget.new
  end

  def create
    @model = Widget.new(model_params)
    if @model.save
      redirect_to admin_widgets_path, :notice => "Successfully created widget."
    else
      render :new
    end
  end

  def edit
    @h1 = 'Edit widget'
  end

  def update
    if @model.update_attributes(model_params)
      redirect_to admin_widgets_path, :notice => "Successfully updated widget."
    else
      render :edit
    end
  end

  def destroy
    @model = Widget.find(params[:id])
    @model.destroy
    redirect_to admin_widgets_path, :notice => "Successfully destroyed widget."
  end

  private

  def get_model
    @model = Widget.find(params[:id])
  end

  def model_params
    params.require(:widget).permit(
        :name,
        :wname,
        :sort,
        :position_id
    )
  end
end

app/helpers/admin/widgets_helper.rb
module Admin::WidgetsHelper
end

app/views/widgets/_banners_on_main_widget.html.erb
<% if posts_in_header.present? && !posts_in_header[:first].nil? %>
  <div class="section">
    <div class="container">
      <div id="hot-post" class="row hot-post">
        <div class="col-md-8 hot-post-left">
          <div class="post post-thumb">
            <%= render partial: 'posts/image', locals: {post: posts_in_header[:first], category: posts_in_header[:first].category} if posts_in_header[:first].image.present? %>
            <div class="post-body">
              <div class="post-category">
                <%= render partial: 'categories/links', collection: posts_in_header[:first].categories, as: :category if posts_in_header[:first].categories.present? %>
              </div>
              <h3 class="post-title title-lg">
                <%= link_to posts_in_header[:first].name, post_path(posts_in_header[:first].category.alias, posts_in_header[:first].alias) %></h3>
              <ul class="post-meta">
                <li><%= link_to posts_in_header[:first].user.profile.name, profile_path(posts_in_header[:first].user.profile) if posts_in_header[:first].user.try(:profile).present? %></li>
                <li><%= posts_in_header[:first].created_at.strftime('%d-%m-%Y') %></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-4 hot-post-right">

          <% posts_in_header[:group].each do |post| %>
            <div class="post post-thumb">
              <%= render partial: 'posts/image', locals: {post: post, category: post.category} if post.image.present? %>
              <div class="post-body">
                <div class="post-category">
                  <%= render partial: 'categories/links', collection: post.categories, as: :category if post.categories.present? %>
                </div>
                <h3 class="post-title"><%= link_to post.name, post_path(post.category.alias, post.alias) %>
                </h3>
                <ul class="post-meta">
                  <li><%= link_to post.user.profile.name, profile_path(post.user.profile) if post.user.try(:profile).present? %></li>
                  <li><%= post.created_at.strftime('%d-%m-%Y') %></li>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/widgets/_category_widget.html.erb
<% if @categories.present? %>
  <div class="aside-widget">
    <div class="section-title">
      <h2 class="title">Categories</h2>
    </div>
    <div class="category-widget">
      <ul>
        <%= render partial: 'shared/blocks/category_item_list', collection: @categories, as: :category, cached: true %>
      </ul>
    </div>
  </div>
<% end %>

app/views/widgets/_galery_widget.html.erb
<div class="aside-widget">
  <div class="section-title">
    <h2 class="title">Instagram</h2>
  </div>
  <div class="galery-widget">
    <ul>
      <li><a href="#"><%= image_tag "galery-1.jpg" %></a></li>
      <li><a href="#"><%= image_tag "galery-2.jpg" %></a></li>
      <li><a href="#"><%= image_tag "galery-3.jpg" %></a></li>
      <li><a href="#"><%= image_tag "galery-4.jpg" %></a></li>
      <li><a href="#"><%= image_tag "galery-5.jpg" %></a></li>
      <li><a href="#"><%= image_tag "galery-6.jpg" %></a></li>
    </ul>
  </div>
</div>

app/views/widgets/_newsletter_widget.html.erb
<div class="aside-widget">
  <div class="section-title">
    <h2 class="title">Newsletter</h2>
  </div>
  <div class="newsletter-widget">
    <form>
      <p>Nec feugiat nisl pretium fusce id velit ut tortor pretium.</p>
      <input class="input" name="newsletter" placeholder="Enter Your Email">
      <button class="primary-button">Subscribe</button>
    </form>
  </div>
</div>

app/views/widgets/_post_author_widget.html.erb
<% if @model.user.present? %>
  <div class="section-row">
    <div class="section-title">
      <h3 class="title">About <%= link_to @model.user.profile.name, profile_path(@model.user.profile) %></h3>
    </div>
    <div class="author media">
      <div class="media-left">
        <%= link_to profile_path(@model.user.profile) do %>
          <%= image_tag @model.user.profile.image.name, class: 'author-img media-object' if @model.user.profile.image.present? %>
        <% end %>
      </div>
      <div class="media-body">
        <p><%= @model.user.profile.description %></p>
        <ul class="author-social">
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
          <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/widgets/_post_widget.html.erb
<div class="aside-widget">
  <div class="section-title">
    <h2 class="title">Popular Posts</h2>
  </div>
  <%= render partial: 'posts/post_sidebar', collection: @popular_posts, as: :post, cached: true %>
</div>

app/views/widgets/_posts_from_categories_v2_widget.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="section-title">
          <h2 class="title">Lifestyle</h2>
        </div>
        <%= render partial: 'posts/post_v4', collection: posts_from_categories([1], 1), as: :post, cached: true %>
      </div>
      <div class="col-md-4">
        <div class="section-title">
          <h2 class="title">Fashion</h2>
        </div>
        <%= render partial: 'posts/post_v4', collection: posts_from_categories([2], 1), as: :post, cached: true %>
      </div>
      <div class="col-md-4">
        <div class="section-title">
          <h2 class="title">Health</h2>
        </div>
        <%= render partial: 'posts/post_v4', collection: posts_from_categories([5], 1), as: :post, cached: true %>
      </div>
    </div>
  </div>
</div>

app/views/widgets/_posts_from_categories_v3_widget.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <% get_posts(9).in_groups_of(3) do |group| %>
        <div class="col-md-4">
          <%= render partial: 'posts/post_v6', collection: group, as: :post, cached: true %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/widgets/_posts_from_categories_widget.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="section-title">
      <h2 class="title">Lifestyle</h2>
    </div>
  </div>
  <%= render partial: 'posts/post_from_categories', collection: posts_from_categories([1], 3), as: :post, cached: true %>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="section-title">
      <h2 class="title">Fashion & Travel</h2>
    </div>
  </div>
  <%= render partial: 'posts/post_from_categories', collection: posts_from_categories([2, 3], 3), as: :post, cached: true %>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="section-title">
      <h2 class="title">Technology & Health</h2>
    </div>
  </div>
  <%= render partial: 'posts/post_from_categories', collection: posts_from_categories([4, 5], 3), as: :post, cached: true %>
</div>

app/views/widgets/_prev_next_post_widget.html.erb
<%
  prev_post = PostsRepository.prev(@model)
  next_post = PostsRepository.next(@model)
%>
<div class="section-row">
  <div class="post-nav">
    <% if prev_post.present? %>
      <div class="prev-post">
        <%= render partial: 'posts/image', locals: {post: prev_post, category: prev_post.category} if prev_post.image.present? %>
        <h3 class="post-title"><%= link_to prev_post.name, post_path(prev_post.category.alias, prev_post.alias) %></h3>
        <span>Previous post</span>
      </div>
    <% end %>

    <% if next_post.present? %>
      <div class="next-post">
        <%= render partial: 'posts/image', locals: {post: next_post, category: next_post.category} if next_post.image.present? %>
        <h3 class="post-title"><%= link_to next_post.name, post_path(next_post.category.alias, next_post.alias) %></h3>
        <span>Next post</span>
      </div>
    <% end %>
  </div>
</div>

app/views/widgets/_recent_posts_widget.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="section-title">
      <h2 class="title">Recent posts</h2>
    </div>
  </div>
  <%= render partial: 'posts/recent_post', collection: recent_posts, as: :post, cached: true %>
</div>

app/views/widgets/_related_posts_widget.html.erb
<div>
  <div class="section-title">
    <h3 class="title">Related Posts</h3>
  </div>
  <div class="row">
    <%= render partial: 'posts/post_from_categories', collection: PostsRepository.related(@model), as: :post, cached: true %>
  </div>
</div>

app/views/widgets/_social_widget.html.erb
<div class="aside-widget">
  <div class="section-title">
    <h2 class="title">Social Media</h2>
  </div>
  <div class="social-widget">
    <ul>
      <li>
        <a href="#" class="social-facebook">
          <i class="fa fa-facebook"></i>
          <span>21.2K<br>Followers</span>
        </a>
      </li>
      <li>
        <a href="#" class="social-twitter">
          <i class="fa fa-twitter"></i>
          <span>10.2K<br>Followers</span>
        </a>
      </li>
      <li>
        <a href="#" class="social-google-plus">
          <i class="fa fa-google-plus"></i>
          <span>5K<br>Followers</span>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/widgets/_tags_widget.html.erb
<div class="footer-widget">
  <h3 class="footer-title">Tags</h3>
  <div class="tags-widget">
    <ul>
      <% get_tags.each do |taggging| %>
        <li><%= link_to taggging.tag.name, tags_path(taggging.tag.name) %></li>
      <% end %>
    </ul>
  </div>
</div>