config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }, path_names: {sign_in: 'login', sign_out: 'logout'}

  root to: "index#show", page_alias: 'home', as: 'home'

  namespace :admin do
    get '', to: "index#index", as: 'home_admin'
    resources :categories, :posts, :pages, :users, :widgets, :widget_positions, :roles, :tags
    resources :comments, except: [:create]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
    end
  end

  resources :comments, only: [:destroy]

  resources :profiles, only: [:show, :update]

  post 'comments/add', to: 'comments#add'
  post 'blog/add_post', to: 'posts#add_post', as: 'add_post'

  get 'blog/:category_alias', to: 'categories#show', as: 'category'
  get 'blog/:category_alias/:post_alias', to: 'posts#show', as: 'post'
  get 'search', to: 'search#show', as: 'search'
  get 'tags/:tag', to: 'tags#show', as: 'tags'
  get 'get-pagination', to: 'application#get_pagination', as: 'pagination'
  get ':page_alias', to: 'pages#show', as: 'page'
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users_roles
  has_many :users, through: :users_roles
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::AdminController
  before_action :get_model, only: [:edit, :update, :show]

  def index
    @h1 = 'Roles'
    @model = Role.all.paginate(:page => params[:page])
  end

  def new
    @h1 = 'Create role'
    @model = Role.new
  end

  def create
    @model = Role.new(model_params)
    if @model.save
      redirect_to admin_roles_path, :notice => "Successfully created role."
    else
      render :new
    end
  end

  def edit
    @h1 = 'Edit role'
  end

  def update
    if @model.update_attributes(model_params)
      redirect_to admin_roles_path, :notice => "Successfully updated role."
    else
      render :edit
    end
  end

  def destroy
    @model = Role.find(params[:id])
    @model.destroy
    redirect_to admin_roles_path, :notice => "Successfully destroyed role."
  end

  private

  def get_model
    @model = Role.find(params[:id])
  end

  def model_params
    params.require(:role).permit(
        :name
    )
  end
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/views/admin/roles/_form.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header d-flex p-0"></div>
      <%= nested_form_for [:admin, @model], html: {multipart: true} do |f| %>
        <div class="card-body">
          <div class="tab-content">
            <div class="tab-pane active" id="tab_1">
              <div class="row">
                <div class="col-md-8">

                  <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                  </div>

                </div>
              </div>
            </div>
            <div class="tab-pane" id="tab_2">
              <div class="row">
                <div class="col-md-8">

                </div>
              </div>
            </div>
            <div class="tab-pane" id="tab_3">
              <div class="row">
                <div class="col-md-8">

                </div>
              </div>
            </div>
          </div>
          <br>
          <%= submit_tag 'Save', class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/roles/_role_item_list.html.erb
<tr class="jsgrid-row">
  <td class="jsgrid-cell"><%= role.id %></td>
  <td class="jsgrid-cell"><%= role.name %></td>
  <td class="jsgrid-cell">&nbsp;
    <%= link_to edit_admin_role_path(role) do %>
      <i class="fa fa-edit"></i>
    <% end %>
    &nbsp;
    <%= link_to admin_role_path(role), method: :delete, data: {:confirm => 'Are you sure?'} do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/admin/roles/edit.html.erb
<%= render 'form' %>

app/views/admin/roles/index.html.erb
<div class="row">
  <div class="col-12">
    <%= link_to 'Create role', new_admin_role_path, role: 'button', class: 'mb-4 btn btn-primary' %>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <div id="jsGrid1" class="jsgrid">
      <table class="jsgrid-table">
        <tr class="jsgrid-header-row">
          <th style="width:50px;" class="jsgrid-header-cell">id</th>
          <th class="jsgrid-header-cell">name</th>
          <th style="width:80px;" class="jsgrid-header-cell"></th>
        </tr>
        <%= render partial: 'admin/roles/role_item_list', collection: @model, as: 'role' %>
      </table>
      <%= will_paginate @model, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/admin/roles/new.html.erb
<%= render 'form' %>